[profile.default]
evm_version = "osaka"
solc = "0.8.35"
optimizer = true
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "@anoma/evm-protocol-adapter/=lib/evm-protocol-adapter/contracts/src/",
]

ignored_warnings_from = [
    "lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/utils", # Warning 6335: "error" will be promoted to keyword in the future and will not be allowed as an identifier anymore.
    "lib/openzeppelin-foundry-upgrades",                                                 # Warning 2018: Function state mutability can be restricted to pure
]

optimizer_runs = 10_000
fuzz = { runs = 1_000 }

out = "out"
src = "src"
libs = ["lib"]
test = "test"
script = "script"

gas_reports = ["XanV1", "XanV2"]

allow_internal_expect_revert = true

[invariant]
runs = 500
depth = 64
fail_on_revert = false

[profile.ci]
fuzz = { runs = 10_000 }
verbosity = 4


[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
localhost = "http://localhost:8545"

# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config
