name: Contracts

on:
  push:
    branches: [main, next]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Contracts Tests
    runs-on: macos-latest
    env:
      FOUNDRY_PROFILE: ci

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Show Bun version
        run: bun --version

      - name: Install Test-Tooling
        run: just tooling

      - name: Run Forge fmt
        run: just fmt-check
        id: fmt

      - name: Run Solhint
        run: just lint
        id: solhint

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Show Slither version
        run: slither --version

      - name: Run Slither
        run: just static-analysis
        id: slither

      - name: Run Forge clean
        run: just clean
        id: clean

      - name: Run Forge build
        run: just build
        id: build

      - name: Run Forge tests
        run: just test
        id: test
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
